/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { TestTaker } from "../../testTaker/base/TestTaker";
import { Question } from "../../question/base/Question";
import { Test } from "../../test/base/Test";

@ObjectType()
class Answer {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  answerContent!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  score!: number | null;

  @ApiProperty({
    required: false,
    type: () => TestTaker,
  })
  @ValidateNested()
  @Type(() => TestTaker)
  @IsOptional()
  testTaker?: TestTaker | null;

  @ApiProperty({
    required: false,
    type: () => Question,
  })
  @ValidateNested()
  @Type(() => Question)
  @IsOptional()
  question?: Question | null;

  @ApiProperty({
    required: false,
    type: () => Test,
  })
  @ValidateNested()
  @Type(() => Test)
  @IsOptional()
  test?: Test | null;
}

export { Answer as Answer };
