/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { QuestionCreateNestedManyWithoutTestsInput } from "./QuestionCreateNestedManyWithoutTestsInput";
import { Type } from "class-transformer";
import { ScoreCreateNestedManyWithoutTestsInput } from "./ScoreCreateNestedManyWithoutTestsInput";
import { AnswerCreateNestedManyWithoutTestsInput } from "./AnswerCreateNestedManyWithoutTestsInput";

@InputType()
class TestCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalMarks?: number | null;

  @ApiProperty({
    required: false,
    type: () => QuestionCreateNestedManyWithoutTestsInput,
  })
  @ValidateNested()
  @Type(() => QuestionCreateNestedManyWithoutTestsInput)
  @IsOptional()
  @Field(() => QuestionCreateNestedManyWithoutTestsInput, {
    nullable: true,
  })
  questions?: QuestionCreateNestedManyWithoutTestsInput;

  @ApiProperty({
    required: false,
    type: () => ScoreCreateNestedManyWithoutTestsInput,
  })
  @ValidateNested()
  @Type(() => ScoreCreateNestedManyWithoutTestsInput)
  @IsOptional()
  @Field(() => ScoreCreateNestedManyWithoutTestsInput, {
    nullable: true,
  })
  scores?: ScoreCreateNestedManyWithoutTestsInput;

  @ApiProperty({
    required: false,
    type: () => AnswerCreateNestedManyWithoutTestsInput,
  })
  @ValidateNested()
  @Type(() => AnswerCreateNestedManyWithoutTestsInput)
  @IsOptional()
  @Field(() => AnswerCreateNestedManyWithoutTestsInput, {
    nullable: true,
  })
  answers?: AnswerCreateNestedManyWithoutTestsInput;
}

export { TestCreateInput as TestCreateInput };
